# Generated by Django 4.2.23 on 2025-07-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pair_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
